kind: ServiceAccount
apiVersion: v1
metadata:
  name: pangeo-forge
  namespace: staging
  labels:
    component: pangeo-forge

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pangeo-forge
  namespace: staging
  labels:
    component: pangeo-forge
rules:
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods/log"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "" # indicates the core API group
  resources:
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pangeo-forge
  namespace: staging
  labels:
    component: pangeo-forge
subjects:
- kind: ServiceAccount
  name: pangeo-forge
roleRef:
  kind: Role
  name: pangeo-forge
  apiGroup: rbac.authorization.k8s.io
